[package]
name = "gh-ac"
version = "1.0.0"
author = "Shawn Yu"
edition = "2021"
# build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.3.2", features = ["derive", "cargo"] }
confy = { version = "0.5.1", features = ["yaml_conf"], default-features = false }
dialoguer = { version = "0.10.4", features = ["fuzzy-select"] }
log = "0.4.18"
serde = "1.0.164"
serde_derive = "1.0.164"
serde_json = "1.0.96"

[build-dependencies]
clap_complete = "4.3.1"
# clap = "*"
clap = { version = "4.3.2", features = ["derive"] }
