name: Generate release

on:
  push:
    branches:
      - master
    # tags:
    # - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: codfish/semantic-release-action@v2
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: cli/gh-extension-precompile@v1
        # TODO: idk why this doesnt work AHHHH
        if: ${{ steps.semantic.outputs.new-release-published }} == true
        with:
          build_script_override: "script/build.sh"
