name: Generate release

on:
  push:
    branches:
      - "**"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: codfish/semantic-release-action@v3
        id: semantic_release
        with:
          branches: |
            [
              {
                name: "master"
              },
              {
                name: "alpha",
                prerelease: true

              }

            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile and upload assets
        uses: cli/gh-extension-precompile@v1
        with:
          go_version: "1.21"
