name: Generate release

on:
  push:
    branches:
      - master
    paths:
      - "src/**"
      - ".github/**"

  pull_request:
    branches:
      - master
    paths:
      - "src/**"
      - ".github/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  actions: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: sudo chmod ugo+rwX .

      - uses: codfish/semantic-release-action@v2
        id: semantic_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update version in Cargo.toml
        if: steps.semantic_release.outputs.new-release-published == 'true'
        uses: ciiiii/toml-editor@1.0.0
        with:
          file: "Cargo.toml"
          key: "package.version"
          value: ${{ steps.semantic_release.outputs.release-version }}

      - run: sudo chmod ugo+rwX .
      - run: ls -la

      - name: Build project
        run: cargo build --release

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(AUTO): update app version [skip ci]"
          branch: master
          create_branch: false

      - uses: cli/gh-extension-precompile@v1
        with:
          build_script_override: "script/build.sh"
